package com.rmsservice1.modal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "policyDocuments")
public class PolicyDocuments {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String policyNumber;

    @DynamoDBAttribute
    private List<String> idProof;

    @DynamoDBAttribute
    private List<String> addressProof;

    @DynamoDBAttribute
    private List<String> policyDocument;

    @DynamoDBAttribute
    private List<String> healthRecord;

    @DynamoDBAttribute
    private List<String> vehicleRc;

    @DynamoDBAttribute
    private List<String> propertyDocuments;

    @DynamoDBAttribute
    private String policyType;

    @DynamoDBAttribute
    private String addedAt;

    @DynamoDBAttribute
    private String updatedAt;

    public PolicyDocuments() {
        super();
    }

    public PolicyDocuments(String id, String policyNumber, List<String> idProof, List<String> addressProof, List<String> policyDocument, List<String> healthRecord, List<String> vehicleRc, List<String> propertyDocuments, String policyType, String addedAt, String updatedAt) {
        this.id = id;
        this.policyNumber = policyNumber;
        this.idProof = idProof;
        this.addressProof = addressProof;
        this.policyDocument = policyDocument;
        this.healthRecord = healthRecord;
        this.vehicleRc = vehicleRc;
        this.propertyDocuments = propertyDocuments;
        this.policyType = policyType;
        this.addedAt = addedAt;
        this.updatedAt = updatedAt;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPolicyNumber() {
        return policyNumber;
    }

    public void setPolicyNumber(String policyNumber) {
        this.policyNumber = policyNumber;
    }

    public List<String> getIdProof() {
        return idProof;
    }

    public void setIdProof(List<String> idProof) {
        this.idProof = idProof;
    }

    public List<String> getAddressProof() {
        return addressProof;
    }

    public void setAddressProof(List<String> addressProof) {
        this.addressProof = addressProof;
    }

    public List<String> getPolicyDocument() {
        return policyDocument;
    }

    public void setPolicyDocument(List<String> policyDocument) {
        this.policyDocument = policyDocument;
    }

    public List<String> getHealthRecord() {
        return healthRecord;
    }

    public void setHealthRecord(List<String> healthRecord) {
        this.healthRecord = healthRecord;
    }

    public List<String> getVehicleRc() {
        return vehicleRc;
    }

    public void setVehicleRc(List<String> vehicleRc) {
        this.vehicleRc = vehicleRc;
    }

    public List<String> getPropertyDocuments() {
        return propertyDocuments;
    }

    public void setPropertyDocuments(List<String> propertyDocuments) {
        this.propertyDocuments = propertyDocuments;
    }

    public String getPolicyType() {
        return policyType;
    }

    public void setPolicyType(String policyType) {
        this.policyType = policyType;
    }

    public String getAddedAt() {
        return addedAt;
    }

    public void setAddedAt(String addedAt) {
        this.addedAt = addedAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
}
